version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      eslint-plugins:
        patterns:
          - '@eslint*'
          - 'eslint-plugin-*'
          - 'eslint-config-*'
          - 'typescript-eslint'
          - '@vue/eslint-config-*'
          - '@nuxt/eslint-config'
      prettier-plugins:
        patterns:
          - 'prettier*'
      stylelint-plugins:
        patterns:
          - 'stylelint*'
      dev-tools:
        patterns:
          - '@commitlint*'
          - '@release-it*'
          - 'husky'
          - 'lint-staged'
          - 'release-it'
          - 'vitest'
          - 'globals'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(deps)'
